# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruckus}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tduehr", "tqbf"]
  s.date = %q{2009-10-23}
  s.description = %q{Ruckus: A DOM-Inspired Ruby Smart Fuzzer}
  s.email = %q{td@matasano.com}
  s.extra_rdoc_files = [
    "README",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/ruckus.rb",
     "lib/ruckus/blob.rb",
     "lib/ruckus/choice.rb",
     "lib/ruckus/dfuzz.rb",
     "lib/ruckus/dictionary.rb",
     "lib/ruckus/enum.rb",
     "lib/ruckus/extensions/array.rb",
     "lib/ruckus/extensions/class.rb",
     "lib/ruckus/extensions/duplicable.rb",
     "lib/ruckus/extensions/file.rb",
     "lib/ruckus/extensions/fixnum.rb",
     "lib/ruckus/extensions/hash.rb",
     "lib/ruckus/extensions/integer.rb",
     "lib/ruckus/extensions/ipaddr.rb",
     "lib/ruckus/extensions/irb.rb",
     "lib/ruckus/extensions/math.rb",
     "lib/ruckus/extensions/module.rb",
     "lib/ruckus/extensions/numeric.rb",
     "lib/ruckus/extensions/object.rb",
     "lib/ruckus/extensions/range.rb",
     "lib/ruckus/extensions/socket.rb",
     "lib/ruckus/extensions/string.rb",
     "lib/ruckus/filter.rb",
     "lib/ruckus/human_display.rb",
     "lib/ruckus/ip.rb",
     "lib/ruckus/mac_addr.rb",
     "lib/ruckus/mutator.rb",
     "lib/ruckus/null.rb",
     "lib/ruckus/number.rb",
     "lib/ruckus/parsel.rb",
     "lib/ruckus/selector.rb",
     "lib/ruckus/str.rb",
     "lib/ruckus/structure.rb",
     "lib/ruckus/structure/atcreate.rb",
     "lib/ruckus/structure/beforebacks.rb",
     "lib/ruckus/structure/defaults.rb",
     "lib/ruckus/structure/factory.rb",
     "lib/ruckus/structure/fixupfields.rb",
     "lib/ruckus/structure/initializers.rb",
     "lib/ruckus/structure/relate.rb",
     "lib/ruckus/structure/replacement.rb",
     "lib/ruckus/structure/searchmods.rb",
     "lib/ruckus/structure/structureproxies.rb",
     "lib/ruckus/structure/validate.rb",
     "lib/ruckus/structure_shortcuts.rb",
     "lib/ruckus/time_t.rb",
     "lib/ruckus/vector.rb",
     "ruckus.gemspec"
  ]
  s.homepage = %q{http://github.com/tduehr/ruckus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A DOM-Inspired Ruby Smart Fuzzer}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

